instructions: >
  This is the text that will be written in the instructional booklet. 
  We can write this tomorrow.
  \n
  \n
  RULES:
  \n
  1. Respect your fellow players, or you're UNCOOL. Yeah.\n
  2. I don't know if \n works in this. If it does, this rule will look weird. Probably doesn't though... argh
coins:
  innocent:
    kill: 8
    survive: 30
  murderer:
    kill: 2
    win: 30
server:
  max-players: 40
  vip-slots: 10