depends: [Votifier, NoCheatPlus]

name: Murder
main: net.minecraftmurder.main.Murder
version: 2.0
description: Minecraft Murder

commands:
   arena:
      description: Commands controlling the arenas.
      usage: /<command> <action> [name] [info-type] [info]
   murder:
      description: Commands controlling the plugin.
      usage: /<command> <action>
   spawn:
      description: Commands controlling spawns.
      usage: /<command> <action>
   coins:
      description: Commands controlling spawns.
      usage: /<command> <action> <player> <count>
   warn:
      description: Commands controlling warns.
      usage: /<command> <player> [rule]

permissions:
    murder.*:
        description: Gives access to all commands
        children:
            murder.core: true
            murder.arenas: true
            murder.spawns: true
            murder.coins: true
            murder.owner: true
            murder.admin: true
            murder.mod: true
    murder.core:
        description: Allows you to control the main plugin
        default: op
    murder.arena:
        description: Allows you to control arenas.
        default: op
    murder.spawn:
        description: Allows you to control spawns.
        default: op
    murder.coins.manage:
        description: Allows you to control coins.
        default: op
    murder.coins:
        description: Allows you to check your coin count.
        default: true
    murder.mod:
        description: Moderator
        default: op
        children:
            murder.joinfull: true
    murder.owner:
        description: Owner
        children:
            murder.core: true
            murder.arenas: true
            murder.spawns: true
            murder.coins.manage: true
            murder.admin: true
            murder.mod: true
            murder.joinfull: true
        default: op
    murder.admin:
        description: Admin
        default: op
        children:
            murder.coins.manage: true
            murder.mod: true
            murder.joinfull: true
    murder.ultra:
        description: Ultra Rank
        default: op
        children:
            murder.vip: true
    murder.vip:
        description: VIP Rank
        default: op
        children:
            murder.joinfull: true
    murder.joinfull:
        description: Join full matches and servers
        default: false